name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

     - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/basic
          build: npx cypress info
