name: Cypress test
on:
  push:
    branches:
      - master
jobs:
  ink-cy-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
      - name: Install Packages
        run: npm install
      - name: Install Cypress
        run: npm install cypress@7.5.0
      
      - name: Run Cypress
        run: ./node_modules/.bin/cypress run