name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: adminRole/cypress
          build: npx cypress info
